
site_locale: 'en_GB'
site_base_url: 'https://christianbrown.uk'
site_name: 'Christian Brown'
site_author: 'Christian Brown'
site_image_name: "Christian Brown's avatar"

header_firstname: 'Christian'
header_lastname: 'Brown'
header_job_title: 'Engineering Manager'
header_location: 'London, UK'

defaults:
  -
    scope:
      path: ""
    values:
      layout: "global"

menu:
  -
    icon: 'download'
    text: 'Download'
    link: '/assets/docs/christian-brown-cv.pdf'
    icon_alt: 'Download icon'
  -
    icon: 'linkedin'
    text: 'Contact me'
    link: 'https://www.linkedin.com/in/christianjbrown/'
    icon_alt: 'LinkedIn icon'

collections:
  - 'previous_roles'
  - 'current_role'
  - 'education'
  - 'volunteering'
